name: Crear y subir imagen docker
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs_on: ubuntu-lastest
    steps:
      - name: checkout
        users: actions/checkout@v4
      - name: construir imagen
        run: docker build -t joelnovo16/ejemplo1:latest
      - name: subir imagen a docker
        run: docker push joelnovo16/ejemplo1:latest