name: Crear y subir imagen docker
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "joelnovo16" --password-stdin
      - name: construir imagen
        run: docker build -t joelnovo16/ejemplo1:latest .
      - name: subir imagen a docker
        run: docker push joelnovo16/ejemplo1:latest